version: 2

# Raw source tables loaded by the ingestion script.
sources:
  - name: raw
    schema: raw
    tables:
      - name: daily_activity
        description: "Raw daily activity CSV data."
      - name: sleep
        description: "Raw sleep CSV data."
