version: 2

models:
  - name: stg_daily_activity
    description: "Staged daily activity data loaded from raw CSVs."
    columns:
      - name: user_id
        description: "User identifier from the device data."
        tests:
          - not_null
      - name: activity_date
        description: "Calendar date for the activity summary."
        tests:
          - not_null
      - name: total_steps
        description: "Total steps recorded for the day."
      - name: total_distance
        description: "Total distance recorded for the day."
      - name: calories
        description: "Estimated calories burned for the day."
  - name: stg_sleep
    description: "Staged sleep data loaded from raw CSVs."
    columns:
      - name: user_id
        description: "User identifier from the device data."
        tests:
          - not_null
      - name: sleep_date
        description: "Calendar date the sleep session belongs to."
        tests:
          - not_null
      - name: total_minutes_asleep
        description: "Minutes asleep during the night."
      - name: total_time_in_bed
        description: "Total minutes spent in bed."
  - name: stg_events
    description: "Staged wearable analytics events from the ingestion API."
    columns:
      - name: event_id
        description: "Unique event identifier."
        tests:
          - not_null
          - unique
      - name: event_name
        description: "Event name."
        tests:
          - not_null
      - name: client_ts
        description: "Client-side timestamp."
        tests:
          - not_null
      - name: server_ts
        description: "Server-side ingestion timestamp."
        tests:
          - not_null
