# Core dbt project configuration for local transformations.
name: "wearable_data_pipeline"
version: "1.0.0"
config-version: 2

profile: "wearable_data_pipeline"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  wearable_data_pipeline:
    +materialized: view
